export const NAVIGATE_REQUEST = 'NAVIGATE_REQUEST';
export const NAVIGATE_SUCCESS = 'NAVIGATE_SUCCESS';
export const NAVIGATE_FAILURE = 'NAVIGATE_FAILURE';

export const CHANGE_COLOR_SCHEME = 'CHANGE_COLOR_SCHEME';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';

export const FETCH_ALL_NEWS_SUCCESS = 'FETCH_ALL_NEWS_SUCCESS';
export const FETCH_ALL_NEWS_FAILURE = 'FETCH_ALL_NEWS_FAILURE';
export const FETCH_ALL_NEWS_REQUEST = 'FETCH_ALL_NEWS_REQUEST';

export const BOOKMARK_NEW = 'BOOKMARK_NEW';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
