export const NAVIGATE_REQUEST = 'NAVIGATE_REQUEST';
export const NAVIGATE_SUCCESS = 'NAVIGATE_SUCCESS';
export const NAVIGATE_FAILURE = 'NAVIGATE_FAILURE';

export const CHANGE_COLOR_SCHEME = 'CHANGE_COLOR_SCHEME';
